#!/bin/bash

#Creates the file touch.sh
touch gitpush.sh


#Makes a clone (copy) of old file called gitpush to gitpull.sh
cp gitpush.sh  gitpull.sh


#Inserts (prints) message from echo into file
echo "git pull" >> gitpull.sh


#Inserts the contents of the first file into the second
cat gitpull.sh >> gitpush.sh

#Mark the two files with excute only privilleges
chmod 755 gitpull.sh
chmod 755 gitpush.sh


#Now go to Lesson 2

#Goes back one directory Changes directory to Lesson_2
#If you made this far.... Its time for  Lesson 2
cd ..


ls 

sleep 1

cd Lesson_2

ls

chmod 755 announcement.sh

source announcement.sh
